Watching for file changes with StatReloader
Unauthorized: /api/favorites/
Unauthorized: /api/favorites/
Unauthorized: /api/favorites/
Unauthorized: /api/favorites/
Unauthorized: /api/favorites/
Unauthorized: /api/favorites/
Unauthorized: /api/favorites/
Unauthorized: /api/favorites/
Not Found: /api/favorites/
Not Found: /api/favorites/
Not Found: /api/favorites/
/home/stifflobster/Projects/Lehae/backend/api/views.py changed, reloading.
Watching for file changes with StatReloader
/home/stifflobster/Projects/Lehae/backend/api/serializers.py changed, reloading.
Watching for file changes with StatReloader
Unauthorized: /api/favorites/
Unauthorized: /api/favorites/
Unauthorized: /api/favorites/
Unauthorized: /api/favorites/
Unauthorized: /api/favorites/
Watching for file changes with StatReloader
Unauthorized: /api/favorites/
Unauthorized: /api/favorites/
Unauthorized: /api/favorites/
Unauthorized: /api/favorites/
Unauthorized: /api/favorites/
Not Found: /api/favorites/
Not Found: /api/favorites/
Not Found: /api/favorites/
Not Found: /api/favorites/
Not Found: /api/favorites/
Not Found: /api/favorites/
Not Found: /api/favorites/
Not Found: /api/favorites/
Not Found: /api/favorites/
Not Found: /api/favorites/
Not Found: /api/favorites/
Not Found: /api/favorites/
Unauthorized: /api/favorites/
Not Found: /api/favorites/
Not Found: /api/favorites/
Not Found: /api/favorites/
Not Found: /api/favorites/
Not Found: /api/favorites/
Not Found: /api/favorites/
Not Found: /api/favorites/
/home/stifflobster/Projects/Lehae/backend/api/serializers.py changed, reloading.
Watching for file changes with StatReloader
Unauthorized: /api/properties/
Unauthorized: /api/properties/
is_favorited for property 1, user 1: False
is_favorited for property 2, user 1: False
is_favorited for property 1, user 1: False
is_favorited for property 8, user 1: False
is_favorited for property 2, user 1: False
is_favorited for property 8, user 1: False
is_favorited for property 1, user 1: False
is_favorited for property 2, user 1: False
is_favorited for property 1, user 1: False
is_favorited for property 8, user 1: False
is_favorited for property 2, user 1: False
is_favorited for property 8, user 1: False
is_favorited for property 1, user 1: False
is_favorited for property 1, user 1: False
is_favorited for property 2, user 1: False
is_favorited for property 2, user 1: False
is_favorited for property 8, user 1: False
is_favorited for property 8, user 1: False
is_favorited for property 1, user 1: False
is_favorited for property 2, user 1: False
is_favorited for property 1, user 1: False
is_favorited for property 8, user 1: False
is_favorited for property 2, user 1: False
is_favorited for property 8, user 1: False
Unauthorized: /api/properties/
is_favorited for property 1, user 1: False
is_favorited for property 2, user 1: False
is_favorited for property 8, user 1: False
Watching for file changes with StatReloader
Unauthorized: /api/properties/
Unauthorized: /api/properties/
is_favorited for property 1, user 1: False
is_favorited for property 1, user 1: False
is_favorited for property 2, user 1: False
is_favorited for property 2, user 1: False
is_favorited for property 8, user 1: False
is_favorited for property 8, user 1: False
is_favorited for property 2, user 1: False
is_favorited for property 2, user 1: False
is_favorited for property 2, user 1: False
is_favorited for property 2, user 1: False
is_favorited for property 2, user 1: False
is_favorited for property 2, user 1: False
is_favorited for property 2, user 1: False
is_favorited for property 1, user 1: False
is_favorited for property 1, user 1: False
is_favorited for property 2, user 1: False
Watching for file changes with StatReloader
is_favorited for property 10, user 9: False
is_favorited for property 11, user 9: False
is_favorited for property 10, user 9: False
Watching for file changes with StatReloader
Unauthorized: /api/favorites/
Bad Request: /api/favorites/
Bad Request: /api/favorites/
Bad Request: /api/favorites/
Bad Request: /api/favorites/
Bad Request: /api/favorites/
Bad Request: /api/favorites/
Bad Request: /api/favorites/
Bad Request: /api/favorites/
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /api/public/properties/
Traceback (most recent call last):
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: api_property.description

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/generics.py", line 203, in get
    return self.list(request, *args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/generics.py", line 175, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/pagination.py", line 222, in paginate_queryset
    return list(self.page)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/core/paginator.py", line 174, in __len__
    return len(self.object_list)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: api_property.description
Internal Server Error: /api/public/properties/
Traceback (most recent call last):
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: api_property.description

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/generics.py", line 203, in get
    return self.list(request, *args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/generics.py", line 175, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/pagination.py", line 222, in paginate_queryset
    return list(self.page)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/core/paginator.py", line 174, in __len__
    return len(self.object_list)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: api_property.description
Internal Server Error: /api/public/properties/
Traceback (most recent call last):
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: api_property.description

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/generics.py", line 203, in get
    return self.list(request, *args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/generics.py", line 175, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/pagination.py", line 222, in paginate_queryset
    return list(self.page)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/core/paginator.py", line 174, in __len__
    return len(self.object_list)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: api_property.description
Internal Server Error: /api/public/properties/
Traceback (most recent call last):
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: api_property.description

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/generics.py", line 203, in get
    return self.list(request, *args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/generics.py", line 175, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/pagination.py", line 222, in paginate_queryset
    return list(self.page)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/core/paginator.py", line 174, in __len__
    return len(self.object_list)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: api_property.description
/home/stifflobster/Projects/Lehae/backend/api/apps.py changed, reloading.
Watching for file changes with StatReloader
/home/stifflobster/Projects/Lehae/backend/backend/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/stifflobster/Projects/Lehae/backend/backend/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/stifflobster/Projects/Lehae/backend/api/apps.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/public/properties/
Traceback (most recent call last):
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: api_property.description

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/generics.py", line 203, in get
    return self.list(request, *args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/generics.py", line 175, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/rest_framework/pagination.py", line 222, in paginate_queryset
    return list(self.page)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/core/paginator.py", line 174, in __len__
    return len(self.object_list)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: api_property.description
Watching for file changes with StatReloader
/home/stifflobster/Projects/Lehae/backend/api/apps.py changed, reloading.
Watching for file changes with StatReloader
/home/stifflobster/Projects/Lehae/backend/api/apps.py changed, reloading.
Watching for file changes with StatReloader
/home/stifflobster/Projects/Lehae/backend/backend/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/stifflobster/Projects/Lehae/backend/backend/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/stifflobster/Projects/Lehae/backend/backend/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/stifflobster/Projects/Lehae/backend/backend/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/stifflobster/Projects/Lehae/backend/backend/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/stifflobster/Projects/Lehae/backend/backend/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/stifflobster/Projects/Lehae/backend/api/apps.py changed, reloading.
Watching for file changes with StatReloader
/home/stifflobster/Projects/Lehae/backend/api/apps.py changed, reloading.
Watching for file changes with StatReloader
Unauthorized: /api/properties/
Unauthorized: /api/token/refresh/
is_favorited for property 1, user 1: False
is_favorited for property 2, user 1: False
is_favorited for property 8, user 1: False
Watching for file changes with StatReloader
/home/stifflobster/Projects/Lehae/backend/api/models.py changed, reloading.
Watching for file changes with StatReloader
/home/stifflobster/Projects/Lehae/backend/api/serializers.py changed, reloading.
Watching for file changes with StatReloader
/home/stifflobster/Projects/Lehae/backend/backend/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Unauthorized: /api/properties/
Unauthorized: /api/token/refresh/
Watching for file changes with StatReloader
/home/stifflobster/Projects/Lehae/backend/api/models.py changed, reloading.
Watching for file changes with StatReloader
/home/stifflobster/Projects/Lehae/backend/api/serializers.py changed, reloading.
Watching for file changes with StatReloader
/home/stifflobster/Projects/Lehae/backend/backend/settings.py changed, reloading.
Watching for file changes with StatReloader
is_favorited for property 1, user 1: False
is_favorited for property 2, user 1: False
is_favorited for property 8, user 1: False
is_favorited for property 1, user 1: False
is_favorited for property 2, user 1: False
is_favorited for property 8, user 1: False
Watching for file changes with StatReloader
Unauthorized: /api/properties/
is_favorited for property 1, user 1: False
is_favorited for property 2, user 1: False
is_favorited for property 8, user 1: False
Importing AvifImagePlugin
Importing BlpImagePlugin
Importing BmpImagePlugin
Importing BufrStubImagePlugin
Importing CurImagePlugin
Importing DcxImagePlugin
Importing DdsImagePlugin
Importing EpsImagePlugin
Importing FitsImagePlugin
Importing FliImagePlugin
Importing FpxImagePlugin
Image: failed to import FpxImagePlugin: No module named 'olefile'
Importing FtexImagePlugin
Importing GbrImagePlugin
Importing GifImagePlugin
Importing GribStubImagePlugin
Importing Hdf5StubImagePlugin
Importing IcnsImagePlugin
Importing IcoImagePlugin
Importing ImImagePlugin
Importing ImtImagePlugin
Importing IptcImagePlugin
Importing JpegImagePlugin
Importing Jpeg2KImagePlugin
Importing McIdasImagePlugin
Importing MicImagePlugin
Image: failed to import MicImagePlugin: No module named 'olefile'
Importing MpegImagePlugin
Importing MpoImagePlugin
Importing MspImagePlugin
Importing PalmImagePlugin
Importing PcdImagePlugin
Importing PcxImagePlugin
Importing PdfImagePlugin
Importing PixarImagePlugin
Importing PngImagePlugin
Importing PpmImagePlugin
Importing PsdImagePlugin
Importing QoiImagePlugin
Importing SgiImagePlugin
Importing SpiderImagePlugin
Importing SunImagePlugin
Importing TgaImagePlugin
Importing TiffImagePlugin
Importing WebPImagePlugin
Importing WmfImagePlugin
Importing XbmImagePlugin
Importing XpmImagePlugin
Importing XVThumbImagePlugin
is_favorited for property 12, user 1: False
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Unauthorized: /api/properties/
Unauthorized: /api/token/refresh/
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
/home/stifflobster/Projects/Lehae/backend/api/models.py changed, reloading.
Watching for file changes with StatReloader
/home/stifflobster/Projects/Lehae/backend/api/serializers.py changed, reloading.
Watching for file changes with StatReloader
/home/stifflobster/Projects/Lehae/backend/api/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Unauthorized: /api/properties/
Not Found: /api/auth/register/
Not Found: /api/auth/register/
Not Found: /api/auth/register/
Not Found: /api/auth/register/
Internal Server Error: /api/public/properties/
Traceback (most recent call last):
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: api_contactmessage.is_read

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/generics.py", line 203, in get
    return self.list(request, *args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: api_contactmessage.is_read
Internal Server Error: /api/public/properties/
Traceback (most recent call last):
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: api_contactmessage.is_read

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/generics.py", line 203, in get
    return self.list(request, *args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: api_contactmessage.is_read
Internal Server Error: /api/public/properties/
Traceback (most recent call last):
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: api_contactmessage.is_read

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/generics.py", line 203, in get
    return self.list(request, *args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: api_contactmessage.is_read
/home/stifflobster/Projects/Lehae/backend/backend/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/stifflobster/Projects/Lehae/backend/api/views.py changed, reloading.
Watching for file changes with StatReloader
Property list error: no such column: api_contactmessage.is_read
Internal Server Error: /api/public/properties/
Property list error: no such column: api_contactmessage.is_read
Internal Server Error: /api/public/properties/
Not Found: /api/auth/register/
Property list error: no such column: api_contactmessage.is_read
Internal Server Error: /api/public/properties/
Property list error: no such column: api_contactmessage.is_read
Internal Server Error: /api/public/properties/
/home/stifflobster/Projects/Lehae/backend/api/models.py changed, reloading.
Watching for file changes with StatReloader
/home/stifflobster/Projects/Lehae/venv/lib/python3.13/site-packages/rest_framework/schemas/utils.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/stifflobster/Projects/Lehae/backend/api/admin.py changed, reloading.
Watching for file changes with StatReloader
Property list error: no such column: api_contactmessage.name
Property list error: no such column: api_contactmessage.name
Internal Server Error: /api/public/properties/
Internal Server Error: /api/public/properties/
Property list error: no such column: api_contactmessage.name
Internal Server Error: /api/public/properties/
Property list error: no such column: api_contactmessage.name
Internal Server Error: /api/public/properties/
Property list error: no such column: api_contactmessage.name
Internal Server Error: /api/public/properties/
Property list error: no such column: api_contactmessage.name
Internal Server Error: /api/public/properties/
Property list error: no such column: api_contactmessage.name
Internal Server Error: /api/public/properties/
Property list error: no such column: api_contactmessage.name
Internal Server Error: /api/public/properties/
Property list error: no such column: api_contactmessage.name
Internal Server Error: /api/public/properties/
Property list error: no such column: api_contactmessage.name
Internal Server Error: /api/public/properties/
Watching for file changes with StatReloader
Property list error: Got AttributeError when attempting to get a value for field `tenant_name` on serializer `ContactMessageSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `ContactMessage` instance.
Original exception text was: 'ContactMessage' object has no attribute 'tenant_name'.
Internal Server Error: /api/public/properties/
Property list error: Got AttributeError when attempting to get a value for field `tenant_name` on serializer `ContactMessageSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `ContactMessage` instance.
Original exception text was: 'ContactMessage' object has no attribute 'tenant_name'.
Internal Server Error: /api/public/properties/
Property list error: Got AttributeError when attempting to get a value for field `tenant_name` on serializer `ContactMessageSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `ContactMessage` instance.
Original exception text was: 'ContactMessage' object has no attribute 'tenant_name'.
Internal Server Error: /api/public/properties/
Property list error: Got AttributeError when attempting to get a value for field `tenant_name` on serializer `ContactMessageSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `ContactMessage` instance.
Original exception text was: 'ContactMessage' object has no attribute 'tenant_name'.
Internal Server Error: /api/public/properties/
Property list error: Got AttributeError when attempting to get a value for field `tenant_name` on serializer `ContactMessageSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `ContactMessage` instance.
Original exception text was: 'ContactMessage' object has no attribute 'tenant_name'.
Internal Server Error: /api/public/properties/
Property list error: Got AttributeError when attempting to get a value for field `tenant_name` on serializer `ContactMessageSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `ContactMessage` instance.
Original exception text was: 'ContactMessage' object has no attribute 'tenant_name'.
Internal Server Error: /api/public/properties/
Property list error: Got AttributeError when attempting to get a value for field `tenant_name` on serializer `ContactMessageSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `ContactMessage` instance.
Original exception text was: 'ContactMessage' object has no attribute 'tenant_name'.
Internal Server Error: /api/public/properties/
Property list error: Got AttributeError when attempting to get a value for field `tenant_name` on serializer `ContactMessageSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `ContactMessage` instance.
Original exception text was: 'ContactMessage' object has no attribute 'tenant_name'.
Internal Server Error: /api/public/properties/
Property list error: Got AttributeError when attempting to get a value for field `tenant_name` on serializer `ContactMessageSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `ContactMessage` instance.
Original exception text was: 'ContactMessage' object has no attribute 'tenant_name'.
Internal Server Error: /api/public/properties/
Property list error: Got AttributeError when attempting to get a value for field `tenant_name` on serializer `ContactMessageSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `ContactMessage` instance.
Original exception text was: 'ContactMessage' object has no attribute 'tenant_name'.
Internal Server Error: /api/public/properties/
Property list error: Got AttributeError when attempting to get a value for field `tenant_name` on serializer `ContactMessageSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `ContactMessage` instance.
Original exception text was: 'ContactMessage' object has no attribute 'tenant_name'.
Internal Server Error: /api/public/properties/
Property list error: Got AttributeError when attempting to get a value for field `tenant_name` on serializer `ContactMessageSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `ContactMessage` instance.
Original exception text was: 'ContactMessage' object has no attribute 'tenant_name'.
Internal Server Error: /api/public/properties/
Property list error: Got AttributeError when attempting to get a value for field `tenant_name` on serializer `ContactMessageSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `ContactMessage` instance.
Original exception text was: 'ContactMessage' object has no attribute 'tenant_name'.
Internal Server Error: /api/public/properties/
Property list error: Got AttributeError when attempting to get a value for field `tenant_name` on serializer `ContactMessageSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `ContactMessage` instance.
Original exception text was: 'ContactMessage' object has no attribute 'tenant_name'.
Internal Server Error: /api/public/properties/
Not Found: /api/auth/register/
Not Found: /api/auth/register/
Not Found: /api/auth/register/
